GET http://localhost:3084/getUsers

####
POST http://localhost:3084/createUsers
Content-Type: application/json


{
    "firstName":"Carlo",
    "lastName": "Atripla",
    "email":"carloatricas@gmail.com",
    "password":"ciaos",
    "age":"30"
}

####
POST http://localhost:3084/login
Content-Type: application/json

{
    "email":"carloatricas@gmail.com",
    "password":"ciaos"
}