GET http://localhost:3084/getUsers

####
POST http://localhost:3084/createUsers
Content-Type: application/json


{
    "firstName":"Carlo",
    "lastName": "Atripla",
    "email":"carloatrica@gmail.com",
    "password":"ciao",
    "age":"30"
}

####
POST http://localhost:3084/login
Content-Type: application/json

{
    "email":"carloatrica@gmail.com",
    "password":"ciao"
}